"use client";

import { Suspense, useEffect, useMemo, useRef, type RefObject } from "react";
import * as THREE from "three";
import { Canvas, useFrame, useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { RoomEnvironment } from "three/examples/jsm/environments/RoomEnvironment.js";

const MODEL_URL = "/scissors-split.glb";

// Index ranges of the three connected components (right half, left half,
// pivot screw) inside scissors-split.glb. Generated by
// scripts/split-scissors.mjs — regenerate and update if the model changes.
const RANGES = {
  right: { start: 0, count: 45888 },
  left: { start: 45888, count: 37824 },
  screw: { start: 83712, count: 54144 },
} as const;

// Centre of the pivot screw in model space; both halves rotate around the
// local y axis through this point (also from scripts/split-scissors.mjs).
const PIVOT = { x: -0.0033, y: -0.0139, z: 0.2405 };

type Keyframe = [progress: number, value: number];

// Piecewise keyframe track with smoothstep easing between neighbours.
function track(p: number, keys: Keyframe[]): number {
  if (p <= keys[0][0]) return keys[0][1];
  for (let i = 1; i < keys.length; i++) {
    if (p <= keys[i][0]) {
      const [t0, v0] = keys[i - 1];
      const [t1, v1] = keys[i];
      const u = (p - t0) / (t1 - t0);
      return v0 + (v1 - v0) * u * u * (3 - 2 * u);
    }
  }
  return keys[keys.length - 1][1];
}

// PMREM-filtered RoomEnvironment gives the bare metal something to reflect
// without fetching an HDRI over the network.
function StudioEnvironment() {
  const gl = useThree((state) => state.gl);
  const scene = useThree((state) => state.scene);

  useEffect(() => {
    const pmrem = new THREE.PMREMGenerator(gl);
    const room = new RoomEnvironment();
    const envMap = pmrem.fromScene(room, 0.04).texture;
    scene.environment = envMap;
    return () => {
      scene.environment = null;
      envMap.dispose();
      pmrem.dispose();
    };
  }, [gl, scene]);

  return null;
}

function ScissorsRig({ progressRef }: { progressRef: RefObject<number> }) {
  const gltf = useGLTF(MODEL_URL);

  const baseGeometry = useMemo(() => {
    let found: THREE.BufferGeometry | null = null;
    gltf.scene.traverse((object) => {
      const mesh = object as THREE.Mesh;
      if (!found && mesh.isMesh) found = mesh.geometry;
    });
    if (!found) throw new Error("scissors mesh missing in " + MODEL_URL);
    return found as THREE.BufferGeometry;
  }, [gltf.scene]);

  // Three geometries sharing the same vertex attributes, differing only in
  // which slice of the (component-ordered) index buffer they draw.
  const parts = useMemo(() => {
    const index = baseGeometry.index;
    if (!index) throw new Error("scissors mesh is not indexed");
    const array = index.array as Uint16Array | Uint32Array;
    const slice = ({ start, count }: { start: number; count: number }) => {
      const geometry = new THREE.BufferGeometry();
      for (const name of Object.keys(baseGeometry.attributes)) {
        geometry.setAttribute(name, baseGeometry.attributes[name]);
      }
      geometry.setIndex(
        new THREE.BufferAttribute(array.subarray(start, start + count), 1)
      );
      return geometry;
    };
    return {
      right: slice(RANGES.right),
      left: slice(RANGES.left),
      screw: slice(RANGES.screw),
    };
  }, [baseGeometry]);

  // Kept deliberately dark: the scissors are a presence behind the
  // typography, not the subject. Warm rim light does the drawing.
  const steel = useMemo(
    () =>
      new THREE.MeshPhysicalMaterial({
        color: new THREE.Color("#a8adb5"),
        metalness: 1,
        roughness: 0.3,
        envMapIntensity: 0.4,
      }),
    []
  );

  useEffect(() => {
    return () => {
      parts.right.dispose();
      parts.left.dispose();
      parts.screw.dispose();
      steel.dispose();
    };
  }, [parts, steel]);

  const dollyRef = useRef<THREE.Group>(null);
  const rollRef = useRef<THREE.Group>(null);
  const spinRef = useRef<THREE.Group>(null);
  const rightRef = useRef<THREE.Group>(null);
  const leftRef = useRef<THREE.Group>(null);

  const smoothed = useRef(0);
  const reduceMotion = useMemo(
    () => window.matchMedia("(prefers-reduced-motion: reduce)").matches,
    []
  );

  useFrame((state, delta) => {
    const dolly = dollyRef.current;
    const roll = rollRef.current;
    const spin = spinRef.current;
    const right = rightRef.current;
    const left = leftRef.current;
    if (!dolly || !roll || !spin || !right || !left) return;

    // Trail the raw scroll progress for a weighted, unhurried feel.
    smoothed.current = THREE.MathUtils.damp(
      smoothed.current,
      progressRef.current,
      6,
      Math.min(delta, 0.1)
    );
    const p = smoothed.current;
    const t = state.clock.elapsedTime;

    // Shrink the composition on narrow viewports so it stays in frame.
    const fit = THREE.MathUtils.clamp(state.viewport.width / 3.6, 0.62, 1);
    const float = reduceMotion ? 0 : Math.sin(t * 0.4) * 0.01;

    // One slow, continuous gesture across the whole section: the scissors
    // hang large and diagonal in the dark, turning with the scroll while
    // the light crawls over the steel.
    const scale = 1.55 * fit * track(p, [[0, 0.94], [1, 1.06]]);
    dolly.position.set(0.12 * fit, 0.05 + float, 0);
    dolly.scale.setScalar(scale);

    spin.rotation.y = track(p, [[0, 0.75], [1, -0.55]]);
    spin.rotation.x = track(p, [[0, 0.18], [1, -0.08]]);
    roll.rotation.z =
      -Math.PI / 2 +
      track(p, [[0, 0.5], [1, 0.18]]) +
      (reduceMotion ? 0 : Math.sin(t * 0.3) * 0.004);

    // The blades breathe once: open through the middle of the section,
    // quietly closed again by the end.
    const phi = track(p, [
      [0.25, 0],
      [0.48, 0.15],
      [0.6, 0.15],
      [0.78, 0],
    ]);
    right.rotation.y = -phi;
    left.rotation.y = phi;
  });

  return (
    <group ref={dollyRef}>
      <group ref={rollRef}>
        <group ref={spinRef}>
          {/* Face the screw side of the scissors towards the camera. */}
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group ref={rightRef}>
              <mesh
                geometry={parts.right}
                material={steel}
                position={[-PIVOT.x, -PIVOT.y, -PIVOT.z]}
              />
            </group>
            <group ref={leftRef}>
              <mesh
                geometry={parts.left}
                material={steel}
                position={[-PIVOT.x, -PIVOT.y, -PIVOT.z]}
              />
            </group>
            <mesh
              geometry={parts.screw}
              material={steel}
              position={[-PIVOT.x, -PIVOT.y, -PIVOT.z]}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

export function ScissorsScene({ progressRef }: { progressRef: RefObject<number> }) {
  return (
    <Canvas
      dpr={[1, 2]}
      camera={{ position: [0, 0, 2.6], fov: 40 }}
      gl={{ antialias: true, alpha: true, powerPreference: "high-performance" }}
    >
      <StudioEnvironment />
      <directionalLight position={[2.5, 2, 3.5]} intensity={0.9} color="#ffe0b0" />
      <directionalLight position={[-3, -1.5, 2]} intensity={0.2} color="#b8c4d8" />
      <Suspense fallback={null}>
        <ScissorsRig progressRef={progressRef} />
      </Suspense>
    </Canvas>
  );
}

useGLTF.preload(MODEL_URL);
